### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Kortex-CR** [uroesch/PlantUMLPortable#32] opened 2020-12-23 14:29 UTC
Hello,
your project interests me a lot as an end user. That's why I wanted to test your alpha release while being aware of the development status.
Not being the admin of my machine, I tried an installation via the dedicated menu of portableapps (paf.exe) which unfortunately ended in failure.
![image](https://user-images.githubusercontent.com/76525044/103007279-68460500-4533-11eb-8328-188844e12314.png)
Do you have an installation alternative in view of my system rights?
Thank you.
Regards.

**Comment by uroesch** [comment] 2020-12-23 17:01
Thanks for showing interest in the PlantUMLPortable installer. The error dialog you attached to the issue report is a generic PortableApps installer error. I will have take a deep dive into the code to find out where it came from so I have a better idea where the problem lies. 

A short test on my end on a plain vanilla Windows 10 PC did not yield the same error as you experienced. But I do understand that your environment is more restricted and confined. To further investigate this issue I'd appreciate if you could answer the handful of questions below. This helps me solving your case. 
1. Have you experienced the same behavior with other PortableApps that you downloaded and executed via the Apps -> Install new App (paf.exe) menu?
2. Have you experienced similar issues when executing `.exe` files. Not necessary the same error message but issues where access to certain parts of the filesystem was not granted.
3. Does the PortableApps installation reside in a directory where you have write access?

#### Troubleshooting tips
I also have a few suggestions and troubleshooting tips how to figure out how to get around your problem. 

##### Installation by specifying a alternate directory`
1. Navigate to the download where the `PlantUMLPortable_1.2020.19-alpha1-uroesch.paf.exe` file is located and run it.
2. When presented with a dialog for the path choose a directory where you have permission to write files. E.g. your home.
![image](https://user-images.githubusercontent.com/12977873/103017960-b4e60c00-4544-11eb-89b2-c9c418cf52fa.png)
3. Observe if you get the same error. If not you may transfer the whole `PlantUMLPortable` directory to your PortableApps installation.

##### Using 7zip to extract the directory content
1. Install and then open 7Zip via PortableApps
![image](https://user-images.githubusercontent.com/12977873/103018222-29b94600-4545-11eb-9615-9d50644a1ef6.png)
2. Navigate to the directory where your `PlantUMLPortable_1.2020.19-alpha1-uroesch.paf.exe` resides right click and go to 7-Zip -> Extract to "PlantUMLPortable_1.2020.19-alpha1-uroesch.paf\"
![image](https://user-images.githubusercontent.com/12977873/103018597-d1cf0f00-4545-11eb-8fff-a37c24cafff1.png)
3. Copy the extracted files to your PortableApps installation; rename the directory PlantUMLPortable and delete the `$PLUGINSDIR` as is only required for the installer.

##### Build it yourself
1. I have built quite a few tools around the build that work both on Linux and Windows. You will require a working installation of `git` and PowerShell to proceed.
2. `git clone --recursive https://github.com/uroesch/PortableApps.git`
3. `cd PortableApps\PlantUMLPortable`
4. `powershell -ExecutionPolicy ByPass -File ./Other/Update/Update.ps1`
While it builds the installer it is not required. After the build finished simply copy the whole directory `PlantUMLPortable` where you started the powershell script to your PortableApps installation. 

Hope this helps. If not let me know, we'll try to find another way. 

cheers, 

--urs

**Comment by Kortex-CR** [comment] 2021-01-05 10:12
Hi,

answers to your mail.


   1. Have you experienced the same behavior with other PortableApps that
   you downloaded and executed via the Apps -> Install new App (paf.exe) menu?
   => Yes, try with freefilesync and it was OK.
   2. Have you experienced similar issues when executing .exe files. Not
   necessary the same error message but issues where access to certain parts
   of the filesystem was not granted.
   => Similar result :(
   [image: image.png]
   3. Does the PortableApps installation reside in a directory where you
   have write access?
   => PortablesApp execution files are localized in my user directory and
   have all authorization except special authorisation.

I have unzip like you explain, the result was ok, i saw PlantUML in the
portable app panel but unfortunately no possibility to run it.
The run command seems to start something closed immediately.

So i had try to install your gitportable app
https://github.com/uroesch/GitPortable/tree/fb077f454eefa55207ddcfe79c4fb061e2c593aa
But the result was the same than PlantUML.

Thank you for your help, I will switch to a development machine (with admin
rights) it will be easier (and in accordance with my company's security
policy ;p ).

Regards.

Le mer. 23 déc. 2020 à 18:01, Urs Roesch <notifications@github.com> a
écrit :

**Comment by uroesch** [comment] 2021-01-05 10:56
Hello Kortex-CR

Thanks for the extensive answers. I will have a look at the issue you mentioned and see if I can get a better understanding of the issue at hand.

As a short note for the PlantUML installation. As it is Java based you will need a version of Java installed. The PortableApps Launcher is written to look first for a version under your `PortableApps\CommonFiles` directory and then choose a version installed on the OS. You may want to install the [OpenJDK JRE](https://portableapps.com/apps/utilities/OpenJDKJRE) as well and try again. 

If you have any further questions regarding the installation procedures please don't hesitate to ask. 

cheers, 

--urs

**Comment by uroesch** [comment] 2023-05-29 09:26
Won't fix, can't reproduce

**Closed** 2023-05-29 09:26 UTC
